import { Inter } from "next/font/google";

import "./globals.css";


const inter = Inter({ subsets: ["latin"], weight:['400','500','600']});

export const metadata = {
  title: "Studio",
  description: "Generated by create next app",
  applicationName:'Studio',
  authors: [{ name: 'Alex' }, { name: 'Semenov', url: 'https://nextjs.org' }],
  creator: 'Alex Semenov',
  publisher: 'Alex Semenov',
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
      'uk-UA': '/uk-UA',
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
